# Generated by Django 6.0.6 on 2026-07-06 21:23

import cars.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[cars.models.validate_car_year])),
                ('mileage', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('city', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarBodyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('hood', 'Hood'), ('roof', 'Roof'), ('trunk', 'Trunk'), ('front_bumper', 'Front bumper'), ('rear_bumper', 'Rear bumper'), ('front_right_fender', 'Front right fender'), ('rear_right_fender', 'Rear right fender'), ('front_left_fender', 'Front left fender'), ('rear_left_fender', 'Rear left fender'), ('front_right_door', 'Front right door'), ('rear_right_door', 'Rear right door'), ('front_left_door', 'Front left door'), ('rear_left_door', 'Rear left door')], max_length=32)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('painted', 'Painted'), ('replaced', 'Replaced'), ('scratch', 'Scratch'), ('dent', 'Dent'), ('repaired', 'Repaired'), ('unknown', 'Unknown')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_conditions', to='cars.car')),
            ],
            options={
                'ordering': ['part'],
                'constraints': [models.UniqueConstraint(fields=('car', 'part'), name='unique_car_body_part')],
            },
        ),
    ]
